### ISSUE TITLE
Add Tidier.jl to R comparison

### ISSUE THREAD

**Issue by kescobo** [BioJulia/biojulia.github.io#11]
https://tidierorg.github.io/TidierData.jl/stable/

**Comment by kdpsingh** [comment]
Our stable docs are really old because I haven't set up a GitHub API key, so use our latest docs instead: https://tidierorg.github.io/TidierData.jl/latest/

**Comment by kdpsingh** [comment]
Actually I see that you referenced the parent package Tidier.jl with the latest docs, which is perfect.

As a side note: Tidier.jl takes a while to install because TidierPlots has a Makie dependency, so if only doing data analysis, TidierData.jl is much faster to install.

**Comment by kescobo** [comment]
@M-PERSIC :point_up:

**Comment by M-PERSIC** [comment]
I'll look into Tidier.jl more this weekend, it might also allow for some fun coding samples!
